title: 我的世界
author: GitHub User
email: whatalittleboy@protonmail.com
description: > # this means to ignore newlines until "twitter_username:"
  feedId:81695876082923520+userId:66751810261381120.Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: ysinx
github_username:  ysinx
rss: rss
# dribbble_username: ysinx
# facebook_username: ysinx
# flickr_username: ysinx
# instagram_username: ysinx
# linkedin_username: ysinx
# pinterest_username: ysinx
# youtube_username: ysinx
# googleplus_username: ysinx

# Mastodon instances
# mastodon:
# - username: ysinx
#   instance: example.com
# - username: ysinx
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
